FROM node:18

# Робоча папка всередині контейнера
WORKDIR /server

# Копіюємо package.json і package-lock.json
COPY server/package*.json ./

# Встановлюємо залежності
RUN npm install

# Копіюємо весь код
COPY server/. .

# Компілія TypeScript
RUN npx tsc

# Відкриваємо порт
EXPOSE 5000

# Запуск сервера
CMD ["node", "build/server.js"]
