version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: Diplom
      POSTGRES_USER: vikaosoba
      POSTGRES_PASSWORD: Feevicun29
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "4000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vikaosoba:Feevicun29@db:5432/Diplom
    depends_on:
      - db
    volumes:
      - ./server/uploads:/server/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
